# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - development

pool:
  vmImage: ubuntu-latest

steps:
  - task: FileTransform@1
    inputs:
      folderPath: "$(System.DefaultWorkingDirectory)"
      fileType: "json"
      targetFiles: "**/appsettings.json"
  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      version: 5.0.x
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview versions
  - task: UseDotNet@2
    inputs:
      version: "3.0.x"
      packageType: runtime
  - task: DotNetCoreCLI@2
    displayName: "NuGet Restore"
    inputs:
      command: restore
      projects: "**/*.csproj"
  - task: DotNetCoreCLI@2
    displayName: "Build Solution"
    inputs:
      command: build
      projects: "**/*.csproj"
      arguments: "--configuration $(buildConfiguration)"
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: "--configuration $(BuildConfiguration) --output $(build.ArtifactStagingDirectory)"
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.ArtifactStagingDirectory)"
      artifactName: "apiPnldCrm"
